import React, { useEffect, useMemo, useState } from 'react';
import { Search, Download, RefreshCw, FileText, Plus } from 'lucide-react';
import { api } from '../services/api';
import { filterReports, REPORT_DATE_RANGES } from '../utils/reportFilters';

interface ReportsListProps {
  canGenerate?: boolean;
}

function statusStyle(status: string): { bg: string; color: string } {
  const s = String(status || '').toLowerCase();
  if (s.includes('complet') || s.includes('closed')) return { bg: '#DCFCE7', color: '#166534' };
  if (s.includes('process') || s.includes('running') || s.includes('pending')) return { bg: '#FEF3C7', color: '#92400E' };
  if (s.includes('fail')) return { bg: '#FEE2E2', color: '#991B1B' };
  return { bg: '#F1F5F9', color: '#475569' };
}

function formatDate(v: any): string {
  if (!v) return '—';
  const d = new Date(v);
  if (Number.isNaN(d.getTime())) return String(v);
  return d.toLocaleDateString();
}

function downloadRowCsv(row: any) {
  const headers = ['Report Name', 'Category', 'Generated On', 'Generated By', 'Status'];
  const cells = [
    row.reportName || '',
    row.category || '',
    row.generatedAt ? new Date(row.generatedAt).toLocaleString() : '',
    row.generatedBy || '',
    row.status || ''
  ].map((c) => `"${String(c).replace(/"/g, '""')}"`);
  const csv = 'data:text/csv;charset=utf-8,' + [headers.join(','), cells.join(',')].join('\n');
  const link = document.createElement('a');
  link.setAttribute('href', encodeURI(csv));
  link.setAttribute('download', `Report_${row.reportId || row.id || 'export'}_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export default function ReportsList({ canGenerate = false }: ReportsListProps) {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [reloadKey, setReloadKey] = useState(0);
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('ALL');
  const [rangeDays, setRangeDays] = useState(30);
  const [generateNote, setGenerateNote] = useState('');

  useEffect(() => {
    let isMounted = true;
    async function load() {
      setLoading(true);
      setError('');
      try {
        const res = await api.getDbReports({ limit: 100 });
        if (!isMounted) return;
        if (res && res.success) {
          const rows = Array.isArray(res.reports) ? res.reports : Array.isArray(res.data) ? res.data : [];
          setReports(rows);
        } else {
          setReports([]);
          setError('Reports are unavailable. The backend could not retrieve live reports.');
        }
      } catch (err: any) {
        if (!isMounted) return;
        setReports([]);
        if (err && (err.status === 403 || err.code === 'FORBIDDEN')) {
          setError('You are not authorized to view reports. Contact your administrator if you need access.');
        } else {
          setError('Reports are unavailable. Check your connection and try again.');
        }
      } finally {
        if (isMounted) setLoading(false);
      }
    }
    load();
    return () => { isMounted = false; };
  }, [reloadKey]);

  const categories = useMemo(() => {
    const set = new Set<string>();
    for (const r of reports) {
      if (r?.category) set.add(String(r.category));
    }
    return ['ALL', ...Array.from(set).sort()];
  }, [reports]);

  const visible = useMemo(
    () => filterReports(reports, { term: search, category, rangeDays }),
    [reports, search, category, rangeDays]
  );

  return (
    <div className="glass-panel animate-fade-in" style={{ padding: '1.5rem 1.75rem', marginBottom: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem', marginBottom: '1.25rem' }}>
        <div>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, margin: 0, color: '#0F172A' }}>Reports</h2>
          <p style={{ color: '#64748B', fontSize: '0.86rem', margin: '0.25rem 0 0 0' }}>View and download audit reports.</p>
        </div>
        {canGenerate && (
          <button
            type="button"
            className="btn btn-primary"
            style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', padding: '0.55rem 1.1rem' }}
            onClick={() => setGenerateNote('Report generation is not available yet — the generation service is pending backend implementation.')}
          >
            <Plus size={15} /> Generate Report
          </button>
        )}
      </div>

      {generateNote && (
        <div role="status" style={{ padding: '0.65rem 0.9rem', backgroundColor: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: '6px', marginBottom: '1rem', fontSize: '0.83rem', color: '#92400E' }}>
          {generateNote}
        </div>
      )}

      <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', marginBottom: '1.1rem' }}>
        <div style={{ position: 'relative', flex: '1 1 220px' }}>
          <Search size={15} style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', color: '#94A3B8' }} />
          <input
            className="form-input"
            style={{ width: '100%', paddingLeft: '2.25rem' }}
            placeholder="Search reports..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            aria-label="Search reports"
          />
        </div>
        <select className="form-select" value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Filter by category" style={{ minWidth: '150px' }}>
          {categories.map((c) => (
            <option key={c} value={c}>{c === 'ALL' ? 'All Categories' : c}</option>
          ))}
        </select>
        <select className="form-select" value={rangeDays} onChange={(e) => setRangeDays(Number(e.target.value))} aria-label="Filter by date range" style={{ minWidth: '140px' }}>
          {REPORT_DATE_RANGES.map((r) => (
            <option key={r.label} value={r.days}>{r.label}</option>
          ))}
        </select>
      </div>

      {loading ? (
        <div>
          {[1, 2, 3].map((n) => (
            <div key={n} style={{ height: '56px', borderRadius: '8px', marginBottom: '0.5rem' }} className="skeleton" />
          ))}
        </div>
      ) : error ? (
        <div role="alert" style={{ padding: '2rem', textAlign: 'center' }}>
          <p style={{ color: 'var(--accent-red)', fontWeight: 700, margin: '0 0 0.5rem 0' }}>Couldn&apos;t load reports.</p>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem', margin: '0 0 1.25rem 0' }}>{error}</p>
          <button type="button" className="btn btn-primary" style={{ padding: '0.6rem 1.5rem' }} onClick={() => setReloadKey((k) => k + 1)}>
            <RefreshCw size={14} style={{ marginRight: '0.4rem' }} /> Retry
          </button>
        </div>
      ) : visible.length === 0 ? (
        <div style={{ padding: '2.5rem 1rem', textAlign: 'center', color: '#64748B' }}>
          <FileText size={30} style={{ color: '#94A3B8', margin: '0 auto 0.6rem auto' }} />
          <div style={{ fontWeight: 600, color: '#334155' }}>No reports found.</div>
          <div style={{ fontSize: '0.82rem', marginTop: '0.25rem' }}>
            {reports.length === 0 ? 'No reports exist in your authorized scope yet.' : 'No reports match your search or filters.'}
          </div>
        </div>
      ) : (
        <div style={{ overflowX: 'auto', border: '1px solid #E2E8F0', borderRadius: '8px' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.86rem' }}>
            <thead>
              <tr style={{ backgroundColor: '#F8FAFC', borderBottom: '1px solid #E2E8F0', color: '#475569' }}>
                <th style={{ padding: '0.85rem 1rem', fontWeight: 700 }}>REPORT NAME</th>
                <th style={{ padding: '0.85rem 1rem', fontWeight: 700 }}>CATEGORY</th>
                <th style={{ padding: '0.85rem 1rem', fontWeight: 700 }}>GENERATED ON</th>
                <th style={{ padding: '0.85rem 1rem', fontWeight: 700 }}>GENERATED BY</th>
                <th style={{ padding: '0.85rem 1rem', fontWeight: 700 }}>STATUS</th>
                <th style={{ padding: '0.85rem 1rem', fontWeight: 700, textAlign: 'center' }}>ACTIONS</th>
              </tr>
            </thead>
            <tbody>
              {visible.map((row: any, idx: number) => {
                const st = statusStyle(row.status);
                return (
                  <tr key={row.reportId || row.id || idx} style={{ borderBottom: '1px solid #F1F5F9' }}>
                    <td style={{ padding: '0.85rem 1rem', fontWeight: 600, color: '#0F172A' }}>{row.reportName || '—'}</td>
                    <td style={{ padding: '0.85rem 1rem', color: '#334155' }}>{row.category || '—'}</td>
                    <td style={{ padding: '0.85rem 1rem', color: '#334155' }}>{formatDate(row.generatedAt)}</td>
                    <td style={{ padding: '0.85rem 1rem', color: '#334155' }}>{row.generatedBy || '—'}</td>
                    <td style={{ padding: '0.85rem 1rem' }}>
                      <span style={{ display: 'inline-block', padding: '0.2rem 0.55rem', fontSize: '0.78rem', fontWeight: 700, borderRadius: '9999px', backgroundColor: st.bg, color: st.color }}>
                        {row.status || '—'}
                      </span>
                    </td>
                    <td style={{ padding: '0.85rem 1rem', textAlign: 'center' }}>
                      <button
                        type="button"
                        onClick={() => downloadRowCsv(row)}
                        title="Download report"
                        aria-label={`Download ${row.reportName || 'report'}`}
                        style={{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem', padding: '0.35rem 0.7rem', fontSize: '0.78rem', borderRadius: '6px', border: '1px solid #CBD5E1', backgroundColor: '#fff', cursor: 'pointer', color: '#1E293B' }}
                      >
                        <Download size={13} /> Download
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
