/**
 * Automated Database Verification Suite for:
 * Story: VY-STRY-31
 * Title: DB: Create VEYRA Reports and Report Execution Schema
 *
 * Verifies all Acceptance Criteria:
 * - AC1: Reports must be persisted with unique IDs (UUID id and UNIQUE report_id).
 * - AC2: Report must reference the user who generated it (user_id FK, generated_by).
 * - AC3: Report category must be persisted.
 * - AC4: Report status must be persisted (with CHECK constraint).
 * - AC5: Generation timestamps must be persisted.
 * - AC6: Report file location stored as reference rather than large file in PostgreSQL.
 * - AC7: Report execution failures must be recorded appropriately in veyra_report_execution.
 * - AC8: Report queries must support: Search, Category, Date range, Status, Generated by.
 * - AC9: Appropriate indexes must be created.
 * - AC10: Database authorization / data-scope design prevents unauthorized report access.
 */

import pg from 'pg';
import dotenv from 'dotenv';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, '../../.env') });
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

const connectionString =
  process.env.DATABASE_URL ||
  `postgresql://${process.env.POSTGRES_USER || 'postgres'}:${process.env.POSTGRES_PASSWORD || 'postgres'}@${process.env.POSTGRES_HOST || '127.0.0.1'}:${process.env.POSTGRES_PORT || '5433'}/${process.env.POSTGRES_DB || 'veyra_db'}`;

const pool = new pg.Pool({ connectionString });

let passedTests = 0;
let failedTests = 0;

function assert(condition: boolean, testName: string, details?: string) {
  if (condition) {
    console.log(`  ✅ [PASS] ${testName}`);
    passedTests++;
  } else {
    console.error(`  ❌ [FAIL] ${testName}`);
    if (details) {
      console.error(`     Details: ${details}`);
    }
    failedTests++;
  }
}

async function runVerification() {
  console.log('========================================================================');
  console.log('  VEYRA Database Verification: VY-STRY-31 Reports & Report Execution Schema');
  console.log(`  Connecting to: ${connectionString.replace(/:[^:@]+@/, ':****@')}`);
  console.log('========================================================================\n');

  try {
    // 1. Ensure migrations are up to date
    execSync('npm run migrate', { cwd: path.resolve(__dirname, '../..'), stdio: 'pipe' });

    // -------------------------------------------------------------------------
    // SECTION 1: Reports Persisted with Unique IDs (AC1)
    // -------------------------------------------------------------------------
    console.log('--- Section 1: Unique ID Persistence (AC1) ---');

    const testRepId1 = `rep_unique_test_${Date.now()}`;
    const insertRes1 = await pool.query(`
      INSERT INTO veyra_report (
        report_id, report_name, report_type, category, status, format,
        generated_by, file_location, application_scope, scope_type
      ) VALUES (
        $1, 'Unique Report Test 1', 'USER_ACCESS', 'User Access & Entitlements',
        'COMPLETED', 'PDF', 'auditor@veyra.local', '/reports/exports/rep_1.pdf',
        'ORACLE_FUSION', 'GLOBAL'
      ) RETURNING id, report_id, created_at;
    `, [testRepId1]);

    assert(insertRes1.rows.length === 1 && insertRes1.rows[0].id, 'TEST 1: Report inserted with unique UUID PK (AC1)');
    const reportUuid1 = insertRes1.rows[0].id;

    // Verify duplicate report_id rejection
    let duplicateRejected = false;
    try {
      await pool.query(`
        INSERT INTO veyra_report (
          report_id, report_name, report_type, category, status, format,
          generated_by, file_location
        ) VALUES (
          $1, 'Duplicate Report Test', 'USER_ACCESS', 'User Access & Entitlements',
          'COMPLETED', 'PDF', 'auditor@veyra.local', '/reports/exports/dup.pdf'
        );
      `, [testRepId1]);
    } catch (err: any) {
      duplicateRejected = err.code === '23505'; // PostgreSQL unique_violation
    }
    assert(duplicateRejected, 'TEST 2: Duplicate report_id rejected by UNIQUE constraint (AC1)');

    // -------------------------------------------------------------------------
    // SECTION 2: User Reference Persistence (AC2)
    // -------------------------------------------------------------------------
    console.log('\n--- Section 2: User Reference Persistence (AC2) ---');

    // Get an existing valid user
    const userRes = await pool.query(`SELECT id, email FROM veyra_user WHERE status = 'ACTIVE' LIMIT 1`);
    assert(userRes.rows.length === 1, 'Found valid existing user for foreign key check');
    const validUserId = userRes.rows[0].id;
    const validUserEmail = userRes.rows[0].email;

    const testRepId2 = `rep_user_ref_${Date.now()}`;
    const insertRes2 = await pool.query(`
      INSERT INTO veyra_report (
        report_id, report_name, report_type, category, status, format,
        generated_by, user_id, file_location, application_scope, scope_type
      ) VALUES (
        $1, 'User Referenced Report', 'ROLE_HIERARCHY', 'Role Hierarchy & Inheritance',
        'COMPLETED', 'CSV', $2, $3, '/reports/exports/rep_2.csv',
        'ORACLE_FUSION', 'USER'
      ) RETURNING id, user_id, generated_by;
    `, [testRepId2, validUserEmail, validUserId]);

    assert(insertRes2.rows[0].user_id === validUserId, 'TEST 3: Report references valid user_id via FK (AC2)');
    assert(insertRes2.rows[0].generated_by === validUserEmail, 'TEST 4: Report generated_by references user identity (AC2)');

    // Verify invalid user_id rejected by FK constraint
    let invalidUserRejected = false;
    try {
      await pool.query(`
        INSERT INTO veyra_report (
          report_id, report_name, report_type, category, status, format,
          generated_by, user_id
        ) VALUES (
          'rep_invalid_fk_test', 'Invalid FK Report', 'ROLE_HIERARCHY', 'Role Hierarchy & Inheritance',
          'COMPLETED', 'CSV', 'unknown@user.com', '00000000-0000-0000-0000-000000000000'
        );
      `, []);
    } catch (err: any) {
      invalidUserRejected = err.code === '23503'; // foreign_key_violation
    }
    assert(invalidUserRejected, 'TEST 5: Non-existent user_id rejected by Foreign Key constraint (AC2)');

    // -------------------------------------------------------------------------
    // SECTION 3: Category and Status Persistence with Constraints (AC3, AC4)
    // -------------------------------------------------------------------------
    console.log('\n--- Section 3: Category & Status Persistence (AC3, AC4) ---');

    const testRepId3 = `rep_cat_stat_${Date.now()}`;
    const insertRes3 = await pool.query(`
      INSERT INTO veyra_report (
        report_id, report_name, report_type, category, status, format,
        generated_by, file_location
      ) VALUES (
        $1, 'Category Status Report', 'SOD_CONFLICTS', 'Segregation of Duties (SoD)',
        'RUNNING', 'EXCEL', 'admin@admin.com', '/reports/exports/rep_3.xlsx'
      ) RETURNING category, status;
    `, [testRepId3]);

    assert(insertRes3.rows[0].category === 'Segregation of Duties (SoD)', 'TEST 6: Category persisted accurately (AC3)');
    assert(insertRes3.rows[0].status === 'RUNNING', 'TEST 7: Status persisted as RUNNING (AC4)');

    // Verify invalid status rejected by check constraint
    let invalidStatusRejected = false;
    try {
      await pool.query(`
        INSERT INTO veyra_report (
          report_id, report_name, report_type, category, status, format, generated_by
        ) VALUES (
          'rep_bad_stat_test', 'Bad Status Report', 'SOD_CONFLICTS', 'Segregation of Duties (SoD)',
          'INVALID_STATUS_VALUE', 'PDF', 'admin@admin.com'
        );
      `);
    } catch (err: any) {
      invalidStatusRejected = err.code === '23514'; // check_violation
    }
    assert(invalidStatusRejected, 'TEST 8: Invalid status value rejected by CHECK constraint (AC4)');

    // -------------------------------------------------------------------------
    // SECTION 4: Timestamps & File Location Reference (AC5, AC6)
    // -------------------------------------------------------------------------
    console.log('\n--- Section 4: Timestamps & File Location Reference (AC5, AC6) ---');

    const repWithLoc = await pool.query(`
      SELECT file_location, generated_at, created_at, updated_at
      FROM veyra_report WHERE report_id = $1;
    `, [testRepId1]);

    const row = repWithLoc.rows[0];
    assert(row.generated_at !== null && row.created_at !== null && row.updated_at !== null, 'TEST 9: Generated, created, updated timestamps populated (AC5)');
    assert(row.file_location === '/reports/exports/rep_1.pdf', 'TEST 10: File location stored as a reference URI/path rather than blob (AC6)');

    // -------------------------------------------------------------------------
    // SECTION 5: Report Execution Failures and Metadata in veyra_report_execution (AC7)
    // -------------------------------------------------------------------------
    console.log('\n--- Section 5: Execution Metadata & Failure Tracking (AC7) ---');

    // 1. Record an execution failure
    const execFailRes = await pool.query(`
      INSERT INTO veyra_report_execution (
        report_id, requested_by, user_id, started_at, completed_at,
        status, error_message, parameters, execution_duration_ms
      ) VALUES (
        $1, 'compliance.officer@veyra.local', $2, NOW() - INTERVAL '20 seconds', NOW(),
        'FAILED', 'Oracle Fusion extraction timed out while reading GL Journal entries.',
        '{"filters":{"period":"2026-09"},"retryCount":3}'::jsonb, 20000
      ) RETURNING id, report_id, status, error_message, parameters;
    `, [reportUuid1, validUserId]);

    assert(execFailRes.rows.length === 1, 'TEST 11: Report execution record inserted into veyra_report_execution (AC7)');
    const execRow = execFailRes.rows[0];
    assert(execRow.status === 'FAILED', 'TEST 12: Execution failure status persisted as FAILED (AC7)');
    assert(execRow.error_message?.includes('Oracle Fusion extraction timed out'), 'TEST 13: Failure error_message recorded accurately (AC7)');
    assert(execRow.parameters?.retryCount === 3, 'TEST 14: Execution parameters stored as JSONB metadata (AC7)');

    // 2. Verify cascading deletion: deleting report cascades to executions
    const testRepDeleteId = `rep_del_test_${Date.now()}`;
    const insertDeleteRep = await pool.query(`
      INSERT INTO veyra_report (
        report_id, report_name, report_type, category, status, format, generated_by
      ) VALUES (
        $1, 'Delete Cascade Test', 'USER_ACCESS', 'User Access & Entitlements', 'FAILED', 'PDF', 'admin@admin.com'
      ) RETURNING id;
    `, [testRepDeleteId]);
    const delRepUuid = insertDeleteRep.rows[0].id;

    await pool.query(`
      INSERT INTO veyra_report_execution (report_id, requested_by, status, error_message)
      VALUES ($1, 'admin@admin.com', 'FAILED', 'Fatal execution crash');
    `, [delRepUuid]);

    await pool.query(`DELETE FROM veyra_report WHERE id = $1`, [delRepUuid]);
    const orphanExec = await pool.query(`SELECT id FROM veyra_report_execution WHERE report_id = $1`, [delRepUuid]);
    assert(orphanExec.rows.length === 0, 'TEST 15: Deleting report cascades to veyra_report_execution records (AC7)');

    // -------------------------------------------------------------------------
    // SECTION 6: Report Queries Supporting Search, Category, Date Range, Status, Generated By (AC8)
    // -------------------------------------------------------------------------
    console.log('\n--- Section 6: Report Query Capabilities (AC8) ---');

    // 1. Search Query
    const searchRes = await pool.query(`
      SELECT report_id, report_name FROM veyra_report
      WHERE report_name ILIKE '%Hierarchy%' OR category ILIKE '%Hierarchy%'
    `);
    assert(searchRes.rows.length > 0, 'TEST 16: Search filter query returns matching reports (AC8)');

    // 2. Category Filter Query
    const catRes = await pool.query(`
      SELECT report_id FROM veyra_report
      WHERE category = 'User Access & Entitlements'
    `);
    assert(catRes.rows.length > 0, 'TEST 17: Category filter query returns matching reports (AC8)');

    // 3. Date Range Filter Query
    const dateRes = await pool.query(`
      SELECT report_id FROM veyra_report
      WHERE generated_at >= NOW() - INTERVAL '30 days' AND generated_at <= NOW() + INTERVAL '1 day'
    `);
    assert(dateRes.rows.length > 0, 'TEST 18: Date range filter query returns matching reports (AC8)');

    // 4. Status Filter Query
    const statusRes = await pool.query(`
      SELECT report_id FROM veyra_report WHERE status = 'COMPLETED'
    `);
    assert(statusRes.rows.length > 0, 'TEST 19: Status filter query returns matching reports (AC8)');

    // 5. Generated By Filter Query
    const genByRes = await pool.query(`
      SELECT report_id FROM veyra_report WHERE generated_by = 'system_scheduler'
    `);
    assert(genByRes.rows.length > 0, 'TEST 20: Generated-by filter query returns matching reports (AC8)');

    // -------------------------------------------------------------------------
    // SECTION 7: Appropriate Indexes Verification (AC9)
    // -------------------------------------------------------------------------
    console.log('\n--- Section 7: Index Verification across Report Tables (AC9) ---');

    const indexRes = await pool.query(`
      SELECT indexname, tablename FROM pg_indexes
      WHERE tablename IN ('veyra_report', 'veyra_report_execution')
    `);
    const indexNames = indexRes.rows.map(r => r.indexname);

    const requiredIndexes = [
      'ix_veyra_report_cat_stat_gen',
      'ix_veyra_report_gen_by_gen',
      'ix_veyra_report_file_loc',
      'ix_veyra_report_generated_at',
      'ix_veyra_report_search_composite',
      'ix_veyra_report_scope_auth',
      'ix_veyra_rep_exec_report_id',
      'ix_veyra_rep_exec_requested_by',
      'ix_veyra_rep_exec_status'
    ];

    for (const idx of requiredIndexes) {
      assert(indexNames.includes(idx), `TEST 21+: Required index ${idx} exists (AC9)`);
    }

    // -------------------------------------------------------------------------
    // SECTION 8: Data-Scope & Authorization Isolation (AC10)
    // -------------------------------------------------------------------------
    console.log('\n--- Section 8: Database Data-Scope & Authorization Design (AC10) ---');

    // Create a private user-scoped report for User A
    const userAScopedRep = `rep_user_a_priv_${Date.now()}`;
    await pool.query(`
      INSERT INTO veyra_report (
        report_id, report_name, report_type, category, status, format,
        generated_by, user_id, scope_type, application_scope
      ) VALUES (
        $1, 'User A Private Report', 'USER_ACCESS', 'User Access & Entitlements',
        'COMPLETED', 'CSV', 'user.a@corp.com', $2, 'USER', 'ORACLE_FUSION'
      );
    `, [userAScopedRep, validUserId]);

    // Query mimicking User B (different user_id): should only see GLOBAL reports, NOT User A's private report
    const userBScopeQuery = await pool.query(`
      SELECT report_id FROM veyra_report
      WHERE application_scope = 'ORACLE_FUSION'
        AND (scope_type = 'GLOBAL' OR (scope_type = 'USER' AND user_id = '99999999-9999-9999-9999-999999999999'))
    `);
    const userBVisibleIds = userBScopeQuery.rows.map(r => r.report_id);
    assert(!userBVisibleIds.includes(userAScopedRep), 'TEST 30: User B cannot query User A private user-scoped report (AC10)');

    // Query mimicking User A: CAN see User A's report
    const userAScopeQuery = await pool.query(`
      SELECT report_id FROM veyra_report
      WHERE application_scope = 'ORACLE_FUSION'
        AND (scope_type = 'GLOBAL' OR (scope_type = 'USER' AND user_id = $1))
    `, [validUserId]);
    const userAVisibleIds = userAScopeQuery.rows.map(r => r.report_id);
    assert(userAVisibleIds.includes(userAScopedRep), 'TEST 31: User A can access own user-scoped report (AC10)');

    // Cleanup test records
    await pool.query(`
      DELETE FROM veyra_report WHERE report_id IN ($1, $2, $3, $4);
    `, [testRepId1, testRepId2, testRepId3, userAScopedRep]);

    console.log('\n========================================================================');
    console.log(`  VERIFICATION RESULT: ${passedTests} PASSED, ${failedTests} FAILED`);
    console.log('========================================================================\n');

    if (failedTests > 0) {
      process.exit(1);
    }
  } catch (err: any) {
    console.error('Unexpected error during verification:', err);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

runVerification();
