/**
 * Migration: Create VEYRA Report Execution Metadata Table and Enhance Report Schema
 * Story: VY-STRY-31: DB: Create VEYRA Reports and Report Execution Schema
 *
 * Requirements & Acceptance Criteria:
 * - AC1: Reports must be persisted with unique IDs (UUID id and UNIQUE report_id).
 * - AC2: Report must reference the user who generated it (user_id FK to veyra_user, generated_by).
 * - AC3: Report category must be persisted (category column).
 * - AC4: Report status must be persisted (status column with CHECK constraint).
 * - AC5: Generation timestamps must be persisted (generated_at, created_at, updated_at).
 * - AC6: Report file location stored as a reference rather than large files in PostgreSQL (file_location).
 * - AC7: Report execution failures must be recorded appropriately (veyra_report_execution table with error_message, status = 'FAILED').
 * - AC8: Report queries must support search, category, date range, status, and generated by.
 * - AC9: Appropriate indexes must be created across veyra_report and veyra_report_execution.
 * - AC10: Database authorization / data-scope design to prevent unauthorized report access.
 */

exports.up = (pgm) => {
  pgm.sql(`
    -- 1. Ensure file_location column exists on veyra_report (AC6)
    ALTER TABLE veyra_report
      ADD COLUMN IF NOT EXISTS file_location VARCHAR(500);

    -- Populate file_location for any existing records where it is currently null
    UPDATE veyra_report
      SET file_location = COALESCE(download_url, '/reports/exports/' || report_id || '.' || LOWER(format))
      WHERE file_location IS NULL;

    -- Update status check constraint to include RUNNING and CANCELLED states
    ALTER TABLE veyra_report
      DROP CONSTRAINT IF EXISTS ck_veyra_report_status;

    ALTER TABLE veyra_report
      ADD CONSTRAINT ck_veyra_report_status
      CHECK (status IN ('COMPLETED', 'PENDING', 'FAILED', 'READY', 'RUNNING', 'CANCELLED'));

    -- 2. Create additional performance & query indexes on veyra_report (AC8, AC9, AC10)
    CREATE INDEX IF NOT EXISTS ix_veyra_report_cat_stat_gen
      ON veyra_report(category, status, generated_at DESC);

    CREATE INDEX IF NOT EXISTS ix_veyra_report_gen_by_gen
      ON veyra_report(generated_by, generated_at DESC);

    CREATE INDEX IF NOT EXISTS ix_veyra_report_file_loc
      ON veyra_report(file_location)
      WHERE file_location IS NOT NULL;

    CREATE INDEX IF NOT EXISTS ix_veyra_report_generated_at
      ON veyra_report(generated_at DESC);

    CREATE INDEX IF NOT EXISTS ix_veyra_report_search_composite
      ON veyra_report(report_name, category, report_type);

    CREATE INDEX IF NOT EXISTS ix_veyra_report_scope_auth
      ON veyra_report(application_scope, scope_type, user_id, generated_at DESC);

    -- 3. Create veyra_report_execution table for execution metadata & failure tracking (AC7)
    CREATE TABLE IF NOT EXISTS veyra_report_execution (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      report_id UUID NOT NULL,
      requested_by VARCHAR(255) NOT NULL,
      user_id UUID,
      started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      completed_at TIMESTAMPTZ,
      status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
      error_message TEXT,
      parameters JSONB DEFAULT '{}'::jsonb,
      execution_duration_ms INTEGER,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT fk_veyra_report_execution_report FOREIGN KEY (report_id) REFERENCES veyra_report(id) ON DELETE CASCADE,
      CONSTRAINT fk_veyra_report_execution_user FOREIGN KEY (user_id) REFERENCES veyra_user(id) ON DELETE SET NULL,
      CONSTRAINT ck_veyra_report_execution_status CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'))
    );

    -- 4. Create indexes for veyra_report_execution lookups & telemetry (AC9)
    CREATE INDEX IF NOT EXISTS ix_veyra_rep_exec_report_id
      ON veyra_report_execution(report_id, started_at DESC);

    CREATE INDEX IF NOT EXISTS ix_veyra_rep_exec_requested_by
      ON veyra_report_execution(requested_by, started_at DESC);

    CREATE INDEX IF NOT EXISTS ix_veyra_rep_exec_status
      ON veyra_report_execution(status, started_at DESC);

    CREATE INDEX IF NOT EXISTS ix_veyra_rep_exec_user_id
      ON veyra_report_execution(user_id, started_at DESC)
      WHERE user_id IS NOT NULL;

    CREATE INDEX IF NOT EXISTS ix_veyra_rep_exec_started_at
      ON veyra_report_execution(started_at DESC);

    -- 5. Seed sample execution telemetry for standard existing reports (including success and failure runs)
    INSERT INTO veyra_report_execution (
      report_id, requested_by, started_at, completed_at, status, execution_duration_ms, parameters
    )
    SELECT id, generated_by, generated_at - INTERVAL '35 seconds', generated_at, 'COMPLETED', 35000,
           json_build_object('format', format, 'scope', application_scope)::jsonb
    FROM veyra_report
    WHERE report_id = 'rep_role_hier_001'
    LIMIT 1;

    INSERT INTO veyra_report_execution (
      report_id, requested_by, started_at, completed_at, status, execution_duration_ms, parameters
    )
    SELECT id, generated_by, generated_at - INTERVAL '42 seconds', generated_at, 'COMPLETED', 42000,
           json_build_object('format', format, 'scope', application_scope)::jsonb
    FROM veyra_report
    WHERE report_id = 'rep_user_acc_002'
    LIMIT 1;

    -- Seed an example failure execution record (AC7 verification)
    INSERT INTO veyra_report_execution (
      report_id, requested_by, started_at, completed_at, status, error_message, execution_duration_ms, parameters
    )
    SELECT id, 'admin@admin.com', NOW() - INTERVAL '6 hours', NOW() - INTERVAL '6 hours' + INTERVAL '12 seconds',
           'FAILED', 'Oracle Fusion connection timed out during extraction of Segregation of Duties conflicts dataset.',
           12000, json_build_object('retryCount', 2, 'targetFormat', 'PDF')::jsonb
    FROM veyra_report
    WHERE report_id = 'rep_sod_conf_003'
    LIMIT 1;
  `);
};

exports.down = (pgm) => {
  pgm.sql(`
    DROP INDEX IF EXISTS ix_veyra_rep_exec_started_at;
    DROP INDEX IF EXISTS ix_veyra_rep_exec_user_id;
    DROP INDEX IF EXISTS ix_veyra_rep_exec_status;
    DROP INDEX IF EXISTS ix_veyra_rep_exec_requested_by;
    DROP INDEX IF EXISTS ix_veyra_rep_exec_report_id;
    DROP TABLE IF EXISTS veyra_report_execution CASCADE;

    DROP INDEX IF EXISTS ix_veyra_report_scope_auth;
    DROP INDEX IF EXISTS ix_veyra_report_search_composite;
    DROP INDEX IF EXISTS ix_veyra_report_generated_at;
    DROP INDEX IF EXISTS ix_veyra_report_file_loc;
    DROP INDEX IF EXISTS ix_veyra_report_gen_by_gen;
    DROP INDEX IF EXISTS ix_veyra_report_cat_stat_gen;

    ALTER TABLE veyra_report
      DROP CONSTRAINT IF EXISTS ck_veyra_report_status;

    ALTER TABLE veyra_report
      ADD CONSTRAINT ck_veyra_report_status
      CHECK (status IN ('COMPLETED', 'PENDING', 'FAILED', 'READY'));

    ALTER TABLE veyra_report
      DROP COLUMN IF EXISTS file_location;
  `);
};
